DROP DATABASE IF EXISTS pcpartsDB;
CREATE DATABASE pcpartsDB;
USE pcpartsDB;

CREATE TABLE pcparts (
    id INT AUTO_INCREMENT NOT NULL,
    name VARCHAR(200) NOT NULL,
    pcpart BOOLEAN DEFAULT false,
    PRIMARY KEY (id)
);